services:
  postgres:
    image: postgres:16
    container_name: pulsepoint-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pulsepoint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gunapriya@123
    ports:
      - "5432:5432"
    volumes:
      - pulsepoint_postgres_data:/var/lib/postgresql/data

volumes:
  pulsepoint_postgres_data:
